name: Go
on: 
  push: 
    branches: [ "main" ] 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v3 

      - name: Set up Go 
        uses: actions/setup-go@v4 
        with: 
          go-version: '1.21.5' 

      - name: Initialize Go Module
        run: |
          if [ ! -f go.mod ]; then
            go mod init github.com/kapsedivya31/lab555
          fi

      - name: Build 
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Upload Binary to S3 
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }} 
          AWS_DEFAULT_REGION: "ap-south-1" 
        run: | 
          aws s3 cp ./addition.go s3://${{ secrets.TARGET_BUCKET }}/
  